CREATE TABLE IF NOT EXISTS MENU (
    ID INT PRIMARY KEY,
    MAINDISH VARCHAR(50) NULL,
    GARRISON VARCHAR(50) NULL,
    SALAD VARCHAR(50) NULL,
    DESSERT VARCHAR(50) NULL,
    DRINK VARCHAR(50) NULL
    );
CREATE TABLE IF NOT EXISTS PERSON (
    NAME VARCHAR(50) PRIMARY KEY,
    PREFERREDMENU INT NULL
    );